=== Javiiloure/Acceso-a-datos/Tarea_10/Ejercicio2/instituto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="instituto">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="alumnos" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="alumno" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="nombre" type="xsd:string" />
                                        <xsd:element name="apellido1" type="xsd:string" />
                                        <xsd:element name="apellido2" type="xsd:string" />
                                        <xsd:element name="telefono">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:pattern
                                                        value="[6][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]" />
                                                    <xsd:length value="9" />
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                    </xsd:sequence>
                                    <xsd:attribute name="dni">
                                        <xsd:simpleType>
                                        <xsd:restriction base="xsd:string">
                                            <xsd:pattern
                                                value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]" />
                                        </xsd:restriction>
                                    </xsd:simpleType>
                                    </xsd:attribute>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="modulos">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="modulo" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="nombre" type="xsd:string" />
                                        <xsd:element name="curso" type="xsd:string" />
                                        <xsd:element name="ciclo" type="xsd:string" />
                                        <xsd:element name="horas" type="xsd:positiveInteger" />
                                    </xsd:sequence>
                                    <xsd:attribute name="id" type="xsd:positiveInteger" use="required" />
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Javiiloure/Acceso-a-datos/Tarea_10/Ejercicio2/instituto.xml
<?xml version="1.0" encoding="UTF-8"?>
<instituto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="instituto.xsd">
    <alumnos>
        <alumno dni="39469661M">
            <nombre>Javier</nombre>
            <apellido1>Loureiro</apellido1>
            <apellido2>Pérez</apellido2>
            <telefono>634616442</telefono>
        </alumno>
        <alumno dni="77013733G">
            <nombre>Sergio</nombre>
            <apellido1>Fernández</apellido1>
            <apellido2>Rodríguez</apellido2>
            <telefono>618575371</telefono>
        </alumno>
    </alumnos>
    <modulos>
        <modulo id="1">
            <nombre>Programación Multimedia</nombre>
            <curso>2º</curso>
            <ciclo>Desarrollo de Aplicaciones Multiplataforma</ciclo>
            <horas>42</horas>
        </modulo>
        <modulo id="2">
            <nombre>Desarrollo de Interfaces</nombre>
            <curso>2º</curso>
            <ciclo>Desarrollo de Aplicaciones Multiplataforma</ciclo>
            <horas>38</horas>
        </modulo>
    </modulos>
</instituto>
